version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3"

  apt_packages:
    - make
    - gettext

  commands:
    - git clone https://github.com/python/cpython.git venv/cpython/
    - python -m pip install --upgrade pip setuptools wheel
    - python -m pip install --upgrade -r requirements.txt -r venv/cpython/Doc/requirements.txt
    - make
    - mkdir -p _readthedocs/html/
    - cp -r venv/cpython/Doc/build/html/* _readthedocs/html/
