parameters:
  BuildToPublish: ''

jobs:
- job: Publish_Store
  displayName: Publish Store packages
  condition: and(succeeded(), eq(variables['DoMSIX'], 'true'), ne(variables['SkipMSIXPublish'], 'true'))

  pool:
    vmImage: windows-2022

  workspace:
    clean: all

  steps:
  - checkout: none

  - ${{ if parameters.BuildToPublish }}:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download artifact: msixupload'
      inputs:
        artifactName: msixupload
        downloadPath: $(Build.BinariesDirectory)
        buildType: specific
        project: cpython
        pipeline: Windows-Release
        buildVersionToDownload: specific
        buildId: ${{ parameters.BuildToPublish }}

  - ${{ else }}:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download artifact: msixupload'
      inputs:
        artifactName: msixupload
        downloadPath: $(Build.BinariesDirectory)

  # TODO: eq(variables['SigningCertificate'], variables['__RealSigningCertificate'])
  # If we are not real-signed, DO NOT PUBLISH
