name: pre-commit-ci
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  pre-commit:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version: "3.11"
          cache: pip

      - name: Install pre-commit
        run: pip install --upgrade -r requirements.txt

      - name: Cache pre-commit tools
        uses: actions/cache@v3
        with:
          key: pre-commit-${{ runner.os }}-${{ steps.setup_python.outputs.python-version}}-${{ hashFiles('.pre-commit-config.yaml') }}
          path: ~/.cache/pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Run pre-commit-ci-lite
        uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
